/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f2884069-ed47-44fb-a864-16072885c6fa",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_7a3BSpNjB",
    "aws_user_pools_web_client_id": "ohb5g76rrkij1ulc3d8b7gcho",
    "oauth": {}
};


export default awsmobile;
